name: CI

on:
  push:
    branches:
      - api-snapshot

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Setup node
      uses: actions/setup-node@v1.4.0
      with:
        node-version: '10.x'

    - name: Install dependencies
      run: npm install
  
    - name: Generate static website
      run: npm run generate
      
    - name: Checkout master branch (storing the static files)
      uses: actions/checkout@v2
      with: 
        ref: master
        path: master
    - name: Update the local copy of the master branch
      run: rsync -avcW dist/ master/ --delete --exclude=".git"
    - name: Commit changes to the master branch
      run: |
        cd master
        git config --local user.email "${{ github.event.pusher.email }}"
        git config --local user.name "${{ github.event.pusher.name }}"
        git add .
        git commit -m "Update master to output generated at ${{ github.sha }}" --allow-empty
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: master
        directory: master
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Rebuild Github pages
      run: curl -u "${{ secrets.GH_PAGES_REBUILD_TOKEN }}" -X POST "https://api.github.com/repos/${{ github.repository }}/pages/builds"
