name: Pull Request

on:
  pull_request:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Setup node
      uses: actions/setup-node@v1.1.0
    - name: Install dependencies
      run: npm install

    - name: Lint code
      run: npm run lint
    - name: Try to generate static website
      run: npm run generate